# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_lesson4.ipynb (unless otherwise specified).

__all__ = ['Sub1', 'il', 'Sub1', 'il', 'Sub1', 'il', 'Sub1', 'il']

# Comes from 03_lesson4.ipynb, cell
class Sub1(Transform[int, int]):
    def __call__(self, x: int) -> int:
        return x - 1

il = ItemList([1,2,3])
assert il._get(2, [Sub1(), Sub1()]) == 1

# Comes from 03_lesson4.ipynb, cell
class Sub1(Transform[int, int]):
    def __call__(self, x: int) -> int:
        return x - 1

il = ItemList([1,2,3])
assert il._get(2, [Sub1(), Sub1()]) == 1

# Comes from 03_lesson4.ipynb, cell
class Sub1(Transform[int, int]):
    def __call__(self, x: int) -> int:
        return x - 1

il = ItemList([1,2,3])
assert il._get(2, [Sub1(), Sub1()]) == 1

# Comes from 03_lesson4.ipynb, cell
class Sub1(Transform[int, int]):
    def __call__(self, x: int) -> int:
        return x - 1

il = ItemList([1,2,3])
assert il._get(2, [Sub1(), Sub1()]) == 1