# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_data": "00_lesson1.ipynb",
         "linear": "00_lesson1.ipynb",
         "relu": "00_lesson1.ipynb",
         "mse": "00_lesson1.ipynb",
         "d_mse": "00_lesson1.ipynb",
         "d_relu": "00_lesson1.ipynb",
         "d_linear": "00_lesson1.ipynb",
         "forward_and_backward": "00_lesson1.ipynb",
         "test_allclose": "00_lesson1.ipynb",
         "Module": "00_lesson1.ipynb",
         "Loss": "00_lesson1.ipynb",
         "Model": "01_lesson2.ipynb",
         "Lin": "00_lesson1.ipynb",
         "ReLU": "00_lesson1.ipynb",
         "MSE": "00_lesson1.ipynb",
         "MNIST_URL": "01_lesson2.ipynb",
         "path": "01_lesson2.ipynb",
         "logsumexp": "01_lesson2.ipynb",
         "log_softmax": "01_lesson2.ipynb",
         "LogSoftmax": "01_lesson2.ipynb",
         "nograd": "01_lesson2.ipynb",
         "Optimizer": "01_lesson2.ipynb",
         "basic_model": "01_lesson2.ipynb",
         "Dataset": "01_lesson2.ipynb",
         "SequentialSampler": "01_lesson2.ipynb",
         "DataLoader": "01_lesson2.ipynb",
         "fit": "01_lesson2.ipynb",
         "Callback": "01_lesson2.ipynb",
         "Learn": "01_lesson2.ipynb",
         "ModelMode": "01_lesson2.ipynb",
         "DataBunch": "01_lesson2.ipynb",
         "Runner": "01_lesson2.ipynb",
         "BasicCallback": "01_lesson2.ipynb",
         "LinearScheduler": "01_lesson2.ipynb",
         "lin_scheduler": "01_lesson2.ipynb",
         "Scheduler": "01_lesson2.ipynb",
         "CosineScheduler": "01_lesson2.ipynb",
         "CombinedScheduler": "01_lesson2.ipynb",
         "Recorder": "01_lesson2.ipynb",
         "get_mnist_data": "02_lesson3.ipynb",
         "stats": "02_lesson3.ipynb",
         "Lambda": "02_lesson3.ipynb",
         "GeneralReLU": "02_lesson3.ipynb",
         "init_cnn_": "02_lesson3.ipynb",
         "conv_layer": "02_lesson3.ipynb",
         "get_model": "02_lesson3.ipynb",
         "current_gpu": "02_lesson3.ipynb",
         "AccuracyCallback": "02_lesson3.ipynb",
         "BatchNorm1d": "02_lesson3.ipynb"}

modules = ["lesson1.py",
           "lesson2.py",
           "lesson3.py"]

doc_url = "https://rforgione.github.io/fastai_part2/"

git_url = "https://github.com/rforgione/fastai_part2/tree/master/"

def custom_doc_links(name): return None
