# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_data": "00_lesson1.ipynb",
         "linear": "00_lesson1.ipynb",
         "relu": "00_lesson1.ipynb",
         "mse": "00_lesson1.ipynb",
         "d_mse": "00_lesson1.ipynb",
         "d_relu": "00_lesson1.ipynb",
         "d_linear": "00_lesson1.ipynb",
         "forward_and_backward": "00_lesson1.ipynb",
         "test_allclose": "00_lesson1.ipynb",
         "Module": "00_lesson1.ipynb",
         "Loss": "00_lesson1.ipynb",
         "Model": "00_lesson1.ipynb",
         "Lin": "00_lesson1.ipynb",
         "ReLU": "00_lesson1.ipynb",
         "MSE": "00_lesson1.ipynb"}

modules = ["lesson1.py"]

doc_url = "https://rforgione.github.io/fastai_part2/"

git_url = "https://github.com/rforgione/fastai_part2/tree/master/"

def custom_doc_links(name): return None
